// apps/web/src/strings.ts — GB-4: every landing-shell word in one table.
// English + Hindi (Devanagari). Game clients keep English for now (open
// follow-up in TICKETS); saga/game content (names, hooks, chapters) is
// content, not chrome, and rides a later content pipeline.
// Usage: t('play.label') / t('play.entering', { id }). Missing Hindi falls
// back to English; missing keys echo the key (loud in tests, quiet in UI).
export type Lang = 'en' | 'hi';

type Table = Record<string, string>;

const en: Table = {
  'meta.title': 'Playground — poke something',
  'kicker.live': 'NO SIGNUP · LINK = ROOM · BOTS NEVER SLEEP',
  'hero.a': "DON'T BROWSE.",
  'hero.b': 'POKE SOMETHING.',
  'hero.sub': 'Zoom through the saga — every chapter ends in a game. Or hit PLAY for the chapter you face.',
  'play.label': '▶ PLAY',
  'play.diving': 'diving…',
  'play.steer': 'steer toward a glowing ring…',
  'play.excavated': 'that world is still being excavated.',
  'play.divingIn': 'diving in — see you inside!',
  'play.entering': 'entering {id}…',
  'play.waking': 'server is waking up — PLAY retries automatically.',
  'play.wakingRetry': 'server is still waking — wait a few seconds, hit PLAY again.',
  'play.roomJoining': 'room {room} · joining as {name}…',
  'play.roomPlaying': 'room {room} · playing as {name}',
  'play.roomFallback': 'room {room} · game client lands in its sprint — server rooms are live now.',
  'play.mountFallback': 'this game is still being excavated. try another portal.',
  'moods.beat': '⚔️ BEAT',
  'moods.chaos': '🎪 CHAOS',
  'moods.think': '🧠 THINK',
  'moods.surprise': '🎲 SURPRISE ME',
  'moodline.beat': 'beat weather — fast rings, faster friends.',
  'moodline.chaos': 'chaos weather — everything sparkles at once.',
  'moodline.think': 'think weather — slow water, deep dive.',
  'moodline.surprise': 'surprise weather — the rift chooses for you.',
  'rift.copy': 'copy my world link',
  'rift.sharePrompt': 'Share this world:',
  'room.kicker': 'ROOM',
  'room.entering': 'Entering…',
  'room.resolving': 'resolving room…',
  'room.back': '← back to the playground',
  'room.mountDefault': 'game client mounts here',
  'finale.aria': 'Saga finale',
  'finale.share': '⚔ CHALLENGE A FRIEND',
  'finale.dive': 'keep diving',
  'finale.copied': 'challenge link copied — send it!',
  'finale.prompt': 'Challenge a friend:',
  'finale.shareText': '{title} — read it before Season 2. {link}',
  'saga.tabsAria': 'Choose a saga',
  'dive.hint': 'scroll / drag to dive · tap to enter',
  'dive.hintStill': 'tap to enter',
  'dive.steer': '✈ steer to fly — dive INTO a glowing ring to play · tap works too',
  'dive.photo': '📸 vista',
  'dive.photoAria': 'Capture this vista as a shareable image',
  'dive.saved': 'vista saved + invite link copied 📸',
  'dive.blocked': 'vista blocked by the browser — screenshot it!',
  'dive.invite': 'I found {name} — come poke it: {link}',
  'dive.aria': 'Endless story dive through six saga chapters. Scroll to turn the page, tap a glowing ring to play.',
  'dive.era': 'ERA {n}/6 · {name}',
  'seal.row': 'Journey: {n} of 6 eras sealed',
  'lang.toggle': 'हिंदी में देखें',
  'studio.failed': 'studio failed to load.',
  'game.connecting': 'connecting…',
  'game.reconnecting': 'reconnecting… (try {n})',
  'game.dropped': 'dropped — rejoining in 1.5s…',
  'game.gain': '+{g} — nice!',
  'game.you': ' (you)',
  'game3d.already': '3D is already on',
  'game3d.loading': 'loading 3D… (one-time, stays 2D if offline)',
  'game3d.offline': 'offline — staying on 2D, fully playable',
  'game3d.pipe': '✨ threepipe {v} 3D on',
  'game3d.three': '✨ three.js {v} 3D on',
  'game3d.failed': '3D failed to start — 2D stays',
  'game3d.dropped': '3D dropped — back on 2D, still playable',
  'rr.score': 'you: {s} · streak x{n}',
  'rr.seated': 'in the room — first rule lands in a second!',
  'rr.gather': 'gathering the room… first rule lands in a second',
  'rr.roundOver': '🏆 ROUND OVER',
  'rr.roundOverSub': 'fresh table in a few seconds — stretch!',
  'rr.smash': 'SMASH',
  'rr.riot': '🎪 RIOT {n}',
  'dd.progress': 'drawing {n}/{t} · you: {s} · streak x{n2}',
  'dd.seated': 'at the table — canvas is live!',
  'dd.reveal': '🎨 it was “{p}” — {n} got it!',
  'dd.draw': '✏️ draw: {p} ({s}s)',
  'dd.watching': '👀 {d} is drawing… ({s}s)',
  'dd.final': '🏆 duel over — fresh canvas soon!',
  'dd.gathering': '🎨 gathering the table…',
  'bz.seated': 'in the drop — loot up!',
  'bz.lobby': 'dropping in… first shrink in 30s',
  'bz.popped': 'popped! spectating — next round auto-starts',
  'bz.alive': 'you: ❤{hp} · 💥{k}',
  'bz.rapid': '⚡ rapid {s}s',
  'bz.zone': '🔥 zone r{r} · {s}s',
  'bz.fire': 'HOLD TO FIRE',
  'bz.aria': 'Blaze squad arena',
  'nr.seated': 'on the grid — pedal down!',
  'nr.lobby': 'heat forms… first across takes it',
  'nr.race': 'P{p} — pads refill boost, bumps cost speed',
  'nr.final': 'heat done — fresh grid in a few seconds',
  'nr.boost': 'BOOST',
  'nr.aria': 'Nitro rift track',
  'ld.rolling': 'rolling…',
  'ld.moving': 'moving…',
  'ld.yourRoll': 'your roll — tap ROLL!',
  'ld.pick': 'pick a glowing token!',
  'ld.thinking': '{n} is thinking…',
  'ld.final': 'game over — fresh table in a few seconds',
  'ld.seated': 'seated — waiting for the table…',
  'ld.turn': '🎲 {n}{you} · {s}s',
  'ld.turnYou': ' (you)',
  'ld.dice': '⚄ {d}',
  'ld.diceNone': '⚄ —',
  'ld.you': 'you {f}/4 · {s}',
  'ld.roll': 'ROLL',
  'ld.aria': 'Ludo board',
  'rm.locked': 'locked in… 🤫',
  'rm.cut': 'your cut: {n} vote{s}',
  'rm.waiting': 'waiting for seats…',
  'rm.seated': 'seated — reading the room…',
  'rm.voteMeta': 'vote who fits — {s}s · no voting yourself',
  'rm.results': '🏆 party results',
  'rm.fresh': 'fresh questions in a few seconds',
  'rm.gathering': 'gathering the party…',
  'rm.you': 'you {s}',
  'rm.tally': '{n}: {v} vote{s}',
  'rm.watching': 'locked in — watching the room… 🤫',
  'rm.tapFit': 'tap who fits best!',
  'rm.readRight': 'you read the room! +2',
  'rm.spoken': 'the room has spoken',
  'rm.champ': '{n} read the room best!',
  'rm.over': 'game over',
  'rm.optYou': '{n}',
  'rm.round': '🔮 Q{n}/{o}',
  'rm.roundNone': '🔮 —',
  'rm.scoreRow': '{n}: {s}',
  'gl.flicked': 'flicked!',
  'gl.yourFlick': 'your flick — drag to aim, release to fire!',
  'gl.rolling': 'rolling…',
  'gl.overSoon': 'run over — fresh course soon',
  'gl.over': 'run over!',
  'gl.seats': 'seats filling — the line forms…',
  'gl.tee': 'on the tee — reading the line…',
  'gl.shots': '🎯 {n} left',
  'gl.noGhost': '👻 no ghost yet',
  'gl.best': '👻 best {b}',
  'gl.seed': '🌱 seed {s}',
  'gl.row': '{mark} {n}{you} {tail}',
  'gl.tailWon': 'in {s}',
  'gl.tailLive': '· {s} shots',
  'gl.aria': 'Ghostline flick course. Drag to aim and release to flick.',
  'sg.reading': 'reading…',
  'sg.spoke': 'the signs spoke! ✨',
  'sg.tap3': 'tap 3 runes, then read!',
  'sg.out': 'out of readings — the tablets decide…',
  'sg.gathering': 'tablets gathering — today\'s signs incoming…',
  'sg.seated': 'seated — today\'s signs incoming…',
  'sg.row': '{mark} {n}{you} {tail}',
  'sg.tailWon': 'in {g}',
  'sg.tailLive': '· {g}',
  'sg.final': 'the day is read — fresh signs soon',
  'sg.tablet': 'YOUR TABLET',
  'sg.go': 'READ THE SIGNS',
  'sg.read': 'READ ✓',
  'sg.empty': 'no readings yet — tap 3 runes, then READ THE SIGNS.',
  'sg.warming': 'the tablet warms up…',
  'sg.left': '🔮 {a}/{m} left',
  'sg.noBest': '🏆 unsolved',
  'sg.best': '🏆 best {b}',
  'sg.day': '🔮 {day} · READ THE SIGNS',
  'tt.placed': 'placed!',
  'tt.spectating': 'spectating — watch and learn!',
  'tt.yourBlock': 'your block — tap the tower to place!',
  'tt.sighting': '{n} is sighting…',
  'tt.hold': 'hold it… ⏳',
  'tt.final': 'settled — fresh timber soon',
  'tt.gathering': 'hands gathering — the raising starts soon…',
  'tt.crew': 'on the crew — timber incoming…',
  'tt.turn': '🗼 {n}{you} · {s}s',
  'tt.turnYou': ' (you!)',
  'tt.settled': '🗼 settled',
  'tt.none': '🗼 —',
  'tt.lean': '⚖️ lean {dir} {bars}',
  'tt.queue': '📦 next {q}',
  'tt.queueNone': '📦 —',
  'tt.row': '{mark} {n}{you} ×{p}',
  'tt.rowYou': ' (you)',
  'tt.aria': 'Totem tower. Tap to place your block where you tap.',
  'rs.lockedIn': 'locked in!',
  'rs.wrecked': 'wrecked this round — next one!',
  'rs.lockedState': 'locked — shots fly soon!',
  'rs.aimState': 'aim! {s}s — drag, then COMMIT',
  'rs.volley': '💥 volley away!',
  'rs.final': 'siege settled — fresh war soon',
  'rs.gathering': 'crews mustering — war starts soon…',
  'rs.arena': 'in the arena — war starts soon…',
  'rs.round': '💥 round {r}/{o}',
  'rs.lock': '🔒 {c}/{n} locked',
  'rs.hp': '❤️ {hp} · 🏆 {w}',
  'rs.go': 'COMMIT',
  'rs.champ': '👑 {n} takes it!',
  'rs.drawn': '🤝 drawn siege!',
  'rs.row': '{mark} {n}{you} {w}W {h}H{lock}',
  'rs.rowYou': ' (you)',
  'rs.rowLock': ' 🔒',
  'rs.you': 'YOU',
  'rs.aria': 'Siege arena. Drag from your hull to aim, then commit.',
  'report.open': '⚠ report',
  'report.title': 'Report a player',
  'report.namePh': 'player name',
  'report.reason': 'reason',
  'report.r-cheating': 'Cheating',
  'report.r-harassment': 'Harassment',
  'report.r-griefing': 'Griefing',
  'report.r-spam': 'Spam',
  'report.r-other': 'Other',
  'report.send': 'Send report',
  'report.cancel': 'Cancel',
  'report.sent': 'report sent — mods will look. thanks.',
  'report.failed': 'report failed — retry?',
  'report.muteTitle': 'Mute taunts',
  'report.mutePh': 'name to mute',
  'report.muteBtn': 'Mute',
  'report.unmute': 'unmute',
  'report.empty': 'nothing muted',
};

const hi: Table = {
  'meta.title': 'Playground — कुछ छेड़ो',
  'kicker.live': 'बिना साइनअप · लिंक = रूम · बॉट कभी सोते नहीं',
  'hero.a': 'देखते मत रहो।',
  'hero.b': 'कुछ छेड़ो।',
  'hero.sub': 'सागा में ज़ूम करो — हर अध्याय एक खेल पर खत्म होता है। या सामने वाले अध्याय के लिए PLAY दबाओ।',
  'play.label': '▶ खेलो',
  'play.diving': 'गोता लग रहा…',
  'play.steer': 'चमकती रिंग की ओर बढ़ो…',
  'play.excavated': 'यह दुनिया अभी बन रही है।',
  'play.divingIn': 'अंदर जा रहे — मिलते हैं!',
  'play.entering': '{id} में प्रवेश…',
  'play.waking': 'सर्वर जाग रहा — PLAY खुद दोबारा कोशिश करेगा।',
  'play.wakingRetry': 'सर्वर अभी जाग रहा — कुछ सेकंड रुको, फिर PLAY दबाओ।',
  'play.roomJoining': 'रूम {room} · {name} बनकर जुड़ रहे…',
  'play.roomPlaying': 'रूम {room} · {name} खेल रहे',
  'play.roomFallback': 'रूम {room} · गेम क्लाइंट अपने स्प्रिंट में आएगा — सर्वर रूम लाइव हैं।',
  'play.mountFallback': 'यह गेम अभी बन रहा है। दूसरा पोर्टल आज़माओ।',
  'moods.beat': '⚔️ जोश',
  'moods.chaos': '🎪 धमाल',
  'moods.think': '🧠 सोच',
  'moods.surprise': '🎲 सरप्राइज़',
  'moodline.beat': 'जोश वाला मौसम — तेज़ रिंग, तेज़ दोस्त।',
  'moodline.chaos': 'धमाल मौसम — सब कुछ एक साथ चमकता है।',
  'moodline.think': 'सोच वाला मौसम — धीमा पानी, गहरा गोता।',
  'moodline.surprise': 'सरप्राइज़ मौसम — रिफ्ट खुद चुनेगा।',
  'rift.copy': 'मेरी दुनिया का लिंक कॉपी करो',
  'rift.sharePrompt': 'यह दुनिया साझा करो:',
  'room.kicker': 'रूम',
  'room.entering': 'प्रवेश हो रहा…',
  'room.resolving': 'रूम सुलझ रहा…',
  'room.back': '← खेल के मैदान पर वापस',
  'room.mountDefault': 'गेम क्लाइंट यहाँ लगेगा',
  'finale.aria': 'सागा समापन',
  'finale.share': '⚔ दोस्त को चुनौती दो',
  'finale.dive': 'गोता जारी रखो',
  'finale.copied': 'चुनौती लिंक कॉपी हुआ — भेज दो!',
  'finale.prompt': 'दोस्त को चुनौती दो:',
  'finale.shareText': '{title} — सीज़न 2 से पहले पढ़ लो। {link}',
  'saga.tabsAria': 'सागा चुनें',
  'dive.hint': 'स्क्रॉल / ड्रैग से गोता · प्रवेश के लिए टैप',
  'dive.hintStill': 'प्रवेश के लिए टैप',
  'dive.steer': '✈ उड़ने के लिए घुमाओ — खेलने के लिए चमकती रिंग में गोता लगाओ · टैप भी चलता है',
  'dive.photo': '📸 नज़ारा',
  'dive.photoAria': 'इस नज़ारे को साझा इमेज बनाकर कैप्चर करो',
  'dive.saved': 'नज़ारा सहेजा + न्योता लिंक कॉपी हुआ 📸',
  'dive.blocked': 'ब्राउज़र ने नज़ारा रोका — स्क्रीनशॉट ले लो!',
  'dive.invite': 'मुझे {name} मिला — आकर छेड़ो: {link}',
  'dive.aria': 'छह सागा अध्यायों में अंतहीन कहानी-गोता। पन्ना पलटने के लिए स्क्रॉल करो, खेलने के लिए चमकती रिंग टैप करो।',
  'dive.era': 'युग {n}/6 · {name}',
  'seal.row': 'यात्रा: 6 में से {n} युग मुहरबंद',
  'lang.toggle': 'View in English',
  'studio.failed': 'स्टूडियो लोड नहीं हुआ।',
  'game.connecting': 'जुड़ रहे…',
  'game.reconnecting': 'फिर जुड़ रहे… (कोशिश {n})',
  'game.dropped': 'छूट गया — 1.5 सेकंड में फिर…',
  'game.gain': '+{g} — बढ़िया!',
  'game.you': ' (तुम)',
  'game3d.already': '3D पहले से चालू है',
  'game3d.loading': '3D लोड हो रहा… (एक बार, ऑफलाइन रहे तो 2D)',
  'game3d.offline': 'ऑफलाइन — 2D पर, पूरा खेलने लायक',
  'game3d.pipe': '✨ थ्रीपाइप {v} 3D चालू',
  'game3d.three': '✨ three.js {v} 3D चालू',
  'game3d.failed': '3D शुरू नहीं हुआ — 2D रहेगा',
  'game3d.dropped': '3D छूटा — 2D पर वापस, खेल चालू',
  'rr.score': 'तुम: {s} · स्ट्रीक x{n}',
  'rr.seated': 'रूम में हो — पहला नियम एक सेकंड में!',
  'rr.gather': 'रूम जुट रहा… पहला नियम एक सेकंड में',
  'rr.roundOver': '🏆 राउंड खत्म',
  'rr.roundOverSub': 'कुछ सेकंड में नई टेबल — अंगड़ाई लो!',
  'rr.smash': 'मारो',
  'rr.riot': '🎪 धमाल {n}',
  'dd.progress': 'ड्राइंग {n}/{t} · तुम: {s} · स्ट्रीक x{n2}',
  'dd.seated': 'टेबल पर हो — कैनवास लाइव है!',
  'dd.reveal': '🎨 यह था "{p}" — {n} ने पकड़ा!',
  'dd.draw': '✏️ बनाओ: {p} ({s} सेकंड)',
  'dd.watching': '👀 {d} बना रहा… ({s} सेकंड)',
  'dd.final': '🏆 मुकाबला खत्म — जल्द नई कैनवास!',
  'dd.gathering': '🎨 टेबल जुट रही…',
  'bz.seated': 'उतर गए — लूटो!',
  'bz.lobby': 'उतर रहे… पहला सिकुड़न 30 सेकंड में',
  'bz.popped': 'फूट गए! देखो — अगला राउंड खुद शुरू होगा',
  'bz.alive': 'तुम: ❤{hp} · 💥{k}',
  'bz.rapid': '⚡ रैपिड {s} सेकंड',
  'bz.zone': '🔥 ज़ोन r{r} · {s} सेकंड',
  'bz.fire': 'दबाकर फायर',
  'bz.aria': 'ब्लेज़ स्क्वाड अखाड़ा',
  'nr.seated': 'ग्रिड पर हो — एक्सीलेटर दबाओ!',
  'nr.lobby': 'हीट बन रही… जो पहले, वो सिकंदर',
  'nr.race': 'P{p} — पैड बूस्ट भरते हैं, टक्कर स्पीड खाती है',
  'nr.final': 'हीट खत्म — कुछ सेकंड में नई ग्रिड',
  'nr.boost': 'बूस्ट',
  'nr.aria': 'नाइट्रो रिफ्ट ट्रैक',
  'ld.rolling': 'घूम रहा…',
  'ld.moving': 'चल रहा…',
  'ld.yourRoll': 'तुम्हारी बारी — ROLL दबाओ!',
  'ld.pick': 'चमकती गोटी चुनो!',
  'ld.thinking': '{n} सोच रहा…',
  'ld.final': 'खेल खत्म — कुछ सेकंड में नई टेबल',
  'ld.seated': 'बैठ गए — टेबल का इंतज़ार…',
  'ld.turn': '🎲 {n}{you} · {s} सेकंड',
  'ld.turnYou': ' (तुम)',
  'ld.dice': '⚄ {d}',
  'ld.diceNone': '⚄ —',
  'ld.you': 'तुम {f}/4 · {s}',
  'ld.roll': 'ROLL',
  'ld.aria': 'लूडो बोर्ड',
  'rm.locked': 'लॉक हुआ… 🤫',
  'rm.cut': 'तुम्हारा हिस्सा: {n} वोट{s}',
  'rm.waiting': 'सीटों का इंतज़ार…',
  'rm.seated': 'बैठ गए — रूम को पढ़ो…',
  'rm.voteMeta': 'जो फिट बैठे उसे वोट — {s} सेकंड · खुद को नहीं',
  'rm.results': '🏆 पार्टी नतीजे',
  'rm.fresh': 'कुछ सेकंड में नए सवाल',
  'rm.gathering': 'पार्टी जुट रही…',
  'rm.you': 'तुम {s}',
  'rm.tally': '{n}: {v} वोट{s}',
  'rm.watching': 'लॉक हुआ — रूम देख रहे… 🤫',
  'rm.tapFit': 'जो सबसे फिट, उसे टैप!',
  'rm.readRight': 'तुमने रूम पढ़ लिया! +2',
  'rm.spoken': 'रूम बोल चुका',
  'rm.champ': '{n} ने रूम सबसे अच्छा पढ़ा!',
  'rm.over': 'खेल खत्म',
  'rm.optYou': '{n}',
  'rm.round': '🔮 प्रश्न {n}/{o}',
  'rm.roundNone': '🔮 —',
  'rm.scoreRow': '{n}: {s}',
  'gl.flicked': 'फ्लिक!',
  'gl.yourFlick': 'तुम्हारा फ्लिक — निशाना लगाकर छोड़ो!',
  'gl.rolling': 'लुढ़क रहा…',
  'gl.overSoon': 'रन खत्म — जल्द नया कोर्स',
  'gl.over': 'रन खत्म!',
  'gl.seats': 'सीटें भर रहीं — लाइन बन रही…',
  'gl.tee': 'टी पर हो — लाइन पढ़ो…',
  'gl.shots': '🎯 {n} बाकी',
  'gl.noGhost': '👻 अभी कोई भूत नहीं',
  'gl.best': '👻 बेस्ट {b}',
  'gl.seed': '🌱 सीड {s}',
  'gl.row': '{mark} {n}{you} {tail}',
  'gl.tailWon': '{s} में',
  'gl.tailLive': '· {s} शॉट',
  'gl.aria': 'घोस्टलाइन फ्लिक कोर्स। निशाना लगाकर छोड़ो।',
  'sg.reading': 'पढ़ रहे…',
  'sg.spoke': 'संकेत बोल उठे! ✨',
  'sg.tap3': '3 रून टैप करो, फिर पढ़ो!',
  'sg.out': 'रीडिंग खत्म — टैबलेट तय करेंगे…',
  'sg.gathering': 'टैबलेट जुट रहे — आज के संकेत आ रहे…',
  'sg.seated': 'बैठ गए — आज के संकेत आ रहे…',
  'sg.row': '{mark} {n}{you} {tail}',
  'sg.tailWon': '{g} में',
  'sg.tailLive': '· {g}',
  'sg.final': 'आज पढ़ लिया गया — जल्द नए संकेत',
  'sg.tablet': 'तुम्हारा टैबलेट',
  'sg.go': 'संकेत पढ़ो',
  'sg.read': 'पढ़ लिया ✓',
  'sg.empty': 'अभी कोई रीडिंग नहीं — 3 रून टैप करो, फिर पढ़ो।',
  'sg.warming': 'टैबलेट गरम हो रहा…',
  'sg.left': '🔮 {a}/{m} बाकी',
  'sg.noBest': '🏆 अनसुलझा',
  'sg.best': '🏆 बेस्ट {b}',
  'sg.day': '🔮 {day} · संकेत पढ़ो',
  'tt.placed': 'रख दिया!',
  'tt.spectating': 'देख रहे — सीखो!',
  'tt.yourBlock': 'तुम्हारा ब्लॉक — टावर पर टैप करो!',
  'tt.sighting': '{n} निशाना लगा रहा…',
  'tt.hold': 'थामे रखो… ⏳',
  'tt.final': 'जम गया — जल्द नई लकड़ी',
  'tt.gathering': 'हाथ जुट रहे — उठान जल्द…',
  'tt.crew': 'दल में हो — लकड़ी आ रही…',
  'tt.turn': '🗼 {n}{you} · {s} सेकंड',
  'tt.turnYou': ' (तुम!)',
  'tt.settled': '🗼 जम गया',
  'tt.none': '🗼 —',
  'tt.lean': '⚖️ झुकाव {dir} {bars}',
  'tt.queue': '📦 अगला {q}',
  'tt.queueNone': '📦 —',
  'tt.row': '{mark} {n}{you} ×{p}',
  'tt.rowYou': ' (तुम)',
  'tt.aria': 'टोटम टावर। अपना ब्लॉक जहाँ रखना है वहाँ टैप करो।',
  'rs.lockedIn': 'लॉक हुआ!',
  'rs.wrecked': 'इस राउंड तबाह — अगला!',
  'rs.lockedState': 'लॉक — गोले जल्द उड़ेंगे!',
  'rs.aimState': 'निशाना! {s} सेकंड — खींचो, फिर COMMIT',
  'rs.volley': '💥 गोले चले!',
  'rs.final': 'घेराबंदी जमी — जल्द नई जंग',
  'rs.gathering': 'दल जुट रहे — जंग जल्द…',
  'rs.arena': 'अखाड़े में हो — जंग जल्द…',
  'rs.round': '💥 राउंड {r}/{o}',
  'rs.lock': '🔒 {c}/{n} लॉक',
  'rs.hp': '❤️ {hp} · 🏆 {w}',
  'rs.go': 'COMMIT',
  'rs.champ': '👑 {n} जीता!',
  'rs.drawn': '🤝 बराबर घेराबंदी!',
  'rs.row': '{mark} {n}{you} {w}W {h}H{lock}',
  'rs.rowYou': ' (तुम)',
  'rs.rowLock': ' 🔒',
  'rs.you': 'तुम',
  'rs.aria': 'घेराबंदी अखाड़ा। अपने गोले से निशाना खींचो, फिर कमिट करो।',
  'report.open': '⚠ रिपोर्ट',
  'report.title': 'खिलाड़ी की रिपोर्ट',
  'report.namePh': 'खिलाड़ी का नाम',
  'report.reason': 'कारण',
  'report.r-cheating': 'धोखा',
  'report.r-harassment': 'उत्पीड़न',
  'report.r-griefing': 'खेल बिगाड़ना',
  'report.r-spam': 'स्पैम',
  'report.r-other': 'अन्य',
  'report.send': 'रिपोर्ट भेजो',
  'report.cancel': 'रद्द करो',
  'report.sent': 'रिपोर्ट गई — मॉड देखेंगे। शुक्रिया।',
  'report.failed': 'रिपोर्ट नहीं गई — फिर कोशिश?',
  'report.muteTitle': 'ताने बंद करो',
  'report.mutePh': 'नाम जिसे चुप करना है',
  'report.muteBtn': 'चुप करो',
  'report.unmute': 'चुप्पी हटाओ',
  'report.empty': 'कोई चुप नहीं',
};

let lang: Lang = 'en';
try {
  const saved = typeof localStorage !== 'undefined' ? localStorage.getItem('pg-lang') : null;
  if (saved === 'hi' || saved === 'en') lang = saved;
} catch { /* private mode speaks English */ }

export function getLang(): Lang { return lang; }

export function setLang(l: Lang): void {
  lang = l;
  try { localStorage.setItem('pg-lang', l); } catch { /* private */ }
}

function fill(s: string, vars?: Record<string, string>): string {
  if (!vars) return s;
  return s.replace(/\{(\w+)\}/g, (m, k: string) => vars[k] ?? m);
}

/** Translate a shell key. Game ids/verbs/hooks are content — never keys. */
export function t(key: string, vars?: Record<string, string>): string {
  const table = lang === 'hi' ? hi : en;
  const s = table[key] ?? en[key] ?? key;
  return fill(s, vars);
}

/** Test seam: every English key and its placeholders. */
export function enKeys(): string[] { return Object.keys(en); }
/** Exported for tests only (same objects, zero bundle cost). */
export const EN_TABLE: Table = en;
export const HI_TABLE: Table = hi;
export function placeholders(s: string): string[] {
  return [...s.matchAll(/\{(\w+)\}/g)].map((m) => m[1]!).sort();
}
